package aiss.luis.model.enumerates;

public enum MontageTheme {
	ANIMALS, FASHION, LANDMARKS, RECEIPTS, WEDDINGS,
	ARTS, FLOWERS, LANDSCAPES, SCREENSHOTS, WHITEBOARDS,
	BIRTHDAYS, FOOD, NIGHT, SELFIES,	 
	CITYSCAPES, GARDENS, PEOPLE, SPORT,	 
	CRAFTS, HOLIDAYS, PERFORMANCES, TRAVEL,	 
	DOCUMENTS, HOUSES, PETS, UTILITY
}
